In [ ]:
import pandas as pd
import re
import datetime as dt
pd.set_option('display.max_colwidth', None)

In [ ]:
####################################
##     Compiled by a C/C++ Expert-
##     Md. Asaduzzaman Jabin
##     Ph.D. Student, ECE, UGA, GA-30602, USA
####################################################################################################################
#                                 This code is done on google colab editor
####################################################################################################################

In [ ]:
#read the TS in Harry Potter 1.csv (note, this is a semicolon separated dataset)
#this dataset was retrieved from https://www.kaggle.com/datasets/gulsahdemiryurek/harry-potter-dataset

df = pd.read_csv("data/Harry Potter 1.csv", sep=';')
df

,Character,Sentence
0,Dumbledore,"I should've known that you would be here, Professor McGonagall."
1,McGonagall,"Good evening, Professor Dumbledore."
2,McGonagall,"Are the rumors true, Albus?"
3,Dumbledore,"I'm afraid so, professor."
4,Dumbledore,The good and the bad.
...,...,...
1582,Hagrid,"Oh, listen, Harry, if that dolt of a cousin of yours, Dudley, gives you any grief, you could always, um, threaten him with a nice pair of ears to go with that tail of his."
1583,Harry,"But Hagrid, we're not allowed to do magic away from Hogwarts. You know that."
1584,Hagrid,"I do. But your cousin don't, do he? Eh? Off you go."
1585,Hermione,"Feels strange to be going home, doesn't it?"
1586,Harry,I'm not going home. Not really.

In [ ]:
#get all sentences that end in a question mark spoken by Ron (hint, use the str.contains method of a series)

df1 = df.query('Character == "Ron"')
index = df1.Sentence.str.contains(r'\?$')
df1[index]

,Character,Sentence
383,Ron,Excuse me. Do you mind?
390,Ron,"I mean, do you really have the...?"
392,Ron,The scar?
412,Ron,"Well, you can't expect him to hang around all day, can you?"
414,Ron,"Pathetic, isn't he?"
417,Ron,Want to see?
497,Ron,"Harry, what is it?"
565,Ron,Can you imagine the look on old McGonagall's face if we were late?
710,Ron,Does anybody feel like...we shouldn't be here?
722,Ron,Alohomora?
859,Ron,What are friends for?
1049,Ron,Wanna play chess?
1051,Ron,Wanna go and visit Hagrid?
1082,Ron,Leg-Locker Curse?
1434,Ron,Do you want to stop Snape from getting that Stone or not?
1548,Ron,All right? You?

In [ ]:
#get all of the sentences that mention both Harry and Ron
index = df.Sentence.str.contains(r"\bHarry.*\b\bRon.*\b|\bRon.*\b.*\bHarry.*\b")
df[index]

      Character                                      Sentence
845  Hermione    If Harry and Ron hadn't come and found me...
861    Hermione                          Ron's right, Harry.

In [ ]:
#get all of the sentences that start with anumber

index = df.Sentence.str.contains(r"^\d.*$")
df[index]

,Character,Sentence
42,Vernon,36. Counted them myself.
43,Dudley,36?! But last year... last year I had 37!
364,Trainmaster,"9 3/4? Think you're being funny, do ya?"
849,McGonagall,5 points will be taken from Gryffindor for your serious lack of judgment.
852,McGonagall,5 points...will be awarded to each of you.
900,Lee Jordan,10 points for Gryffindor!
1009,Harry,15th Century Fiends...Flamel...
1174,Harry,50?!

In [ ]:
#get all sentences that mention a professor at the end of a sentence excluding punctuation, and extract just name of the professor mentioned (hint, concatenate the result of the extract operation with the original dataframe along axis=1) and then dropna() to eliminate the ones that had no mention
df2 = df.Sentence.str.extract(r"\bProfessor\b\s(\b\w*\b)\W*$")
df3 = pd.concat([df2,df], axis =1).dropna()
df3.rename(columns={0:"Mentioned"}, inplace= True)
df3

,Mentioned,Character,Sentence
0,McGonagall,Dumbledore,"I should've known that you would be here, Professor McGonagall."
1,Dumbledore,McGonagall,"Good evening, Professor Dumbledore."
10,McGonagall,Hagrid,Professor McGonagall.
231,Quirrell,Hagrid,"Harry, This is Professor Quirrell."
523,Quirrell,Harry,"Say, Percy, who's that teacher talking to Professor Quirrell?"
840,McGonagall,Hermione,"It's my fault, Professor McGonagall."
1455,Quirrell,Quirrell,"Next to him, who would suspect, ""p-p-poor s-stuttering Professor Quirrell?"""

In [ ]:
#extract quotes contained within any sentence

df2 = df.Sentence.str.extract(r"\"(.*)\"")
df3 = pd.concat([df2,df], axis =1).dropna()
df3.rename(columns={0:"Quoted"}, inplace= True)
df3

,Quoted,Character,Sentence
625,Up.,Madam Hooch,"Stick your right hand over the broom and say, ""Up."""
1007,Use it well.,Harry,"It just said, ""Use it well."""
1178,the four of us.,Malfoy,"I thought you said...""the four of us."""
1286,"After Fluffy, a dragon's gonna be no problem.",Hagrid,"I told him. I said, ""After Fluffy, a dragon's gonna be no problem."""
1455,p-p-poor s-stuttering Professor Quirrell?,Quirrell,"Next to him, who would suspect, ""p-p-poor s-stuttering Professor Quirrell?"""

In [ ]:
#extract the first hyphenated word in each sentence, where the first word is at least 2 characters
df2 = df.Sentence.str.extract(r"((?:\w{2,}-)+\w*)")
df3 = pd.concat([df2,df], axis =1).dropna()
df3.rename(columns={0:"Hyphenated"}, inplace= True)
df3

,Hyphenated,Character,Sentence
195,Non-magic,Hagrid,Non-magic folk.
246,world-class,Boy,It's a world-class racing broom.
266,You-Know-What,Hagrid,It's about You-Know-What in vault you-know-which.
306,He-Who-Must-Not-Be-Named,Ollivander,"After all, He-Who-Must-Not-Be-Named did great things."
338,You-Know-Who,Harry,To You-Know-Who?
400,bogey-flavoured,Ron,George sweared he got a bogey-flavoured one once!
457,rule-breaking,McGonagall,"Any rule-breaking, and you will lose points."
469,hand-me-down,Malfoy,Red hair and a hand-me-down robe?
482,start-of-term,Dumbledore,I have a few start-of-term notices I wish to announce.
484,third-floor,Dumbledore,"Also, our caretaker, Mr. Filch, has asked me to remind you that the third-floor corridor on the right hand side is out of bounds to everyone who does not wish to die a most painful death."
568,pocket-watch,McGonagall,"Perhaps, lt'd be more useful if I were to transfigure Mr. Potter and yourself into a pocket-watch."
573,wand-waving,Snape,There will be no foolish wand-waving or silly incantations in this class.
574,potion-making,Snape,"As such, I don't expect many of you to appreciate the subtle science and exact art that is potion-making."
755,Uh-oh,Oliver,"Eh, not bad, Potter, you'd make a fair beater...Uh-oh."
778,Levio-saaa,Draco,Wingardium Levio-saaa.
931,Whoo-hoo,Hermione,Whoo-hoo!
1082,Leg-Locker,Ron,Leg-Locker Curse?
1205,Nighty-night,Filch,Nighty-night.
1235,half-life,Firenze,"You have slain something so pure that the moment the blood touches your lips, you will have a half-life."
1249,You-Know-Who,Hermione,"You mean, You-Know-Who's out there, right now, in the forest?"
1302,well-protected,McGonagall,"I don't know how you three found out about the stone, but I can assure you it is perfectly well-protected."
1349,plant-thing,Ron,"Lucky this plant-thing is here, really."
1459,counter-curse,Quirrell,Even with Snape muttering his little counter-curse.
1463,Th-then,Harry,Th-then you let the troll in.
1578,good-bye,Hagrid,"Thought you were leaving without saying good-bye, didja?"

In [261]:
#extract a list of long words (>= 10 characters) from all sentences (findall is probably the easiest thing to use) that have at least two long words.  This is easier to do as a regex followed by a subset

df01 = df.Sentence.str.extract(r"(:?\w{10,}\b)(?:.*)(:?\w{10,}\b)")
df2 = '['+df01[0] +', '+ df01[1]+']'
df3 = pd.concat([df2,df], axis =1).dropna()
df3.rename(columns={0:"LongWords"}, inplace= True)
df3

,LongWords,Character,Sentence
198,"[headmaster, Dumbledore]",Hagrid,"he'll be under the finest headmaster that Hogwarts has ever seen, Albus Dumbledore."
454,"[Gryffindor, Hufflepuff]",McGonagall,"They are Gryffindor, Hufflepuff Ravenclaw and Slytherin."
577,"[possession, formidable]",Snape,"Then again, maybe some of you have come to Hogwarts in possession of abilities so formidable that you feel confident enough to not pay attention."
648,"[Understand, themselves]",Madam Hooch,"Understand? If I see a single broom in the air the one riding it will find themselves out of Hogwarts before they can say, Quidditch."
769,"[rudimentary, levitation]",Flitwick,One of a wizard's most rudimentary skills is levitation the ability to make objects fly.
932,"[Gryffindor, Gryffindor]",Crowd,Go go Gryffindor! Go go Gryffindor!
1023,"[Professors, Restricted]",Filch,"Oh, Professors. I found this, in the Restricted Section."
1074,"[ingredients, getfulness]",Hermione,"Alright, what are the 3 most crucial ingredients in a Forgetfulness Potion?"
1089,"[appreciate, Longbottom]",Seamus,"I don't appreciate the insinuation, Longbottom."
1092,"[Dumbledore, rindelwald]",Ron,Dumbledore is particularly famous for his defeat of the dark wizard Grindelwald in 1945.
1108,"[Philosopher, stonishing]",Hermione,The Philosopher's Stone is a legendary substance with astonishing powers. \r
1294,"[Dumbledore, mmediately]",Harry,"We have to see Professor Dumbledore, immediately!"
1308,"[Gryffindors, yourselves]",Snape,"Now, what would three young Gryffindors such as yourselves be doing inside on a day like this?"
1565,"[outstanding, Gryffindor]",Dumbledore,"And third, to Mr. Harry Potter, for pure nerve and outstanding courage, I award Gryffindor house 60 points."

In [268]:

#extract sentences where the speaker mentions themselves

a_list = []
df = pd.read_csv("data/Harry Potter 1.csv", sep=';')
#df2 = pd.DataFrame(OrderedDict{'Character': 'x','Sentence': 'y'})

for index, row in df.iterrows():
  s1 = row['Character']
  s2 = row['Sentence']
  #s3 =r'(\b'+ re.escape(s1) +r'\b)'
  #print(s3)
  f = s2.find(s1)

  #print(f>=0)
  if f >-1:
    a_list.append(True)
  else:
    a_list.append(False)

df[a_list]

        Character                                                Sentence
133         Harry                                     Make a wish, Harry.
151        Hagrid  Rubeus Hagrid, Keeper of Keys and Grounds at Hogwarts.
162         Harry                                 I mean, I'm just Harry.
163         Harry                                             Just Harry.
374          Fred                             I'm only joking. I am Fred.
386           Ron                                    I'm Ron, by the way.
387           Ron                                            Ron Weasley.
388         Harry                                I'm Harry. Harry Potter.
433      Hermione                                   I'm Hermione Granger.
435           Ron                                        I'm Ron Weasley.
465        Malfoy                                         And I'm Malfoy.
466        Malfoy                                           Draco Malfoy.
537  Sir Nicholas               I prefer Sir Nicholas, if you don't mind.

In [266]:
#display sentences where any word is repeated 4 or more times (note you may get a warning)
df2 = df.Sentence.str.extract(r"(\b\w{2,}\W){3,}")
#df[df.str.count(r'(^F.*)')==1]
df3 = pd.concat([df2,df], axis =1).dropna()
df3.rename(columns={0:"RepeatedWord"}, inplace= True)
df3

,RepeatedWord,Character,Sentence
0,"here,",Dumbledore,"I should've known that you would be here, Professor McGonagall."
2,"true,",McGonagall,"Are the rumors true, Albus?"
4,bad.,Dumbledore,The good and the bad.
5,boy?,McGonagall,And the boy?
6,him.,Dumbledore,Hagrid is bringing him.
...,...,...,...
1582,of,Hagrid,"Oh, listen, Harry, if that dolt of a cousin of yours, Dudley, gives you any grief, you could always, um, threaten him with a nice pair of ears to go with that tail of his."
1583,Hogwarts.,Harry,"But Hagrid, we're not allowed to do magic away from Hogwarts. You know that."
1584,don',Hagrid,"I do. But your cousin don't, do he? Eh? Off you go."
1585,"home,",Hermione,"Feels strange to be going home, doesn't it?"
1586,home.,Harry,I'm not going home. Not really.